# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.v2.jsonschema.json

version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/davidgaspardev/usermes-backend

linters:
  enable:
    # Official tooling
    - govet

    # High-quality linters
    - staticcheck
    - errcheck
    - ineffassign
    - unused

    # Security & best practices
    - gosec
    - revive

    # Common mistakes
    - bodyclose

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow

  revive:
    rules:
      - name: exported
        disabled: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    - path: cmd/
      linters:
        - revive

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
      colors: true
